services:
  # Our PostgreSQL database
  db:
    # The Docker image of postgres -- we're using the latest.
    image: postgres:latest
    # The ports to expose tp the host calculator
    # 5432 is the default PostgreSQL port
    ports:
      - "5432:5432"
    # If we accidentally kill the running container, Docker Compose
    # will restart it.
    restart: always
      # The PostgreSQL Docker container uses environment variables to
      # read configuration, here we set the password.
      # ⚠️ - Do not store plaintext passwords in source control. We
      #      do so here as this is a builder
    environment:
      POSTGRES_PASSWORD: changemeinprod!


